# busybox: 最小限のOSの機能を備えた非常に軽量なOS
FROM busybox

VOLUME /var/lib/mysql

CMD ["bin/true"]

docker container exec -it 5b55ca68e06c docker container exec -it todo_mysql_master.1.xkee06ztwbyo3eg91kwh4pht3 bash